var k=!0,u=null,w=!1;function ba(a){return function(){return a}}var ca=document.getElementsByTagName("script");var fa=ca[ca.length-1].src.replace(/^[^\?]+\??/,""),ga={};if(fa)for(var ha=fa.split(/[;&]/),ia=0;ia<ha.length;ia++){var ja=ha[ia].split("=");if(ja&&2==ja.length){var ma=unescape(ja[0]),oa=unescape(ja[1]),oa=oa.replace(/\+/g," ");ga[ma]=oa}}var pa=ga.id;
function qa(a){var c=0;a||(a=window.event);a.wheelDelta?c=a.wheelDelta/120:a.detail&&(c=-a.detail/3);c&&(0<c?ra().jsdelta(1):0>c&&ra().jsdelta(-1));a.preventDefault&&a.preventDefault();a.returnValue=w}window.addEventListener&&window.addEventListener("DOMMouseScroll",qa,w);-1!=navigator.appName.indexOf("Microsoft")?document.onmousewheel=qa:window.onmousewheel=qa;function ra(){var a=pa;return-1!=navigator.appName.indexOf("Microsoft")?window[a]:document[a]}var sa,ta,ua,va,wa,U;
function xa(){pa="eMag";ta=sa="";ua=window.location.href;wa=va="";U={};window.useHostedSpeedloaderVar&&(window.speedloaderURLVar="http://sl.readertracking.com/",0<=window.location.hostname.indexOf("emagcloud.com")&&(window.speedloaderURLVar="http://www.emagcloud.com/sl/"),0<=window.location.hostname.indexOf("trial.emagcloud.com")&&(window.speedloaderURLVar="http://trial.emagcloud.com/sl/"),window.speedloaderUIDSURLVar="http://sl.readertracking.com/uids/");0<=ua.indexOf("file:///")?(ya(),V()):window.useSpeedloaderVar?
window.isOpenTrial?(sa="versions/v_",ta="eMagStudio_versions/ver_",window.useHostedSpeedloaderVar?za():Aa()):(sa="versions/v_",ta="eMagStudio_versions/ver_",window.useHostedSpeedloaderVar?Ba():Aa()):(ya(),V())}window.addEventListener?addEventListener("DOMContentLoaded",xa,w):window.onload=xa;function Ba(){var a=window.speedloaderUIDSURLVar+window.uidVar+".jpg",c=new Image;c.onload=function(){za()};c.onerror=function(){ya();V()};c.src=a}
function za(){var a=window.speedloaderURLVar+sa+window.eMagStudioVersionVar+"/test.jpg",c=new Image;c.onload=function(){window.useSpeedloaderVar=k;window.useHostedSpeedloaderVar=k;va=window.speedloaderURLVar+sa+window.eMagStudioVersionVar+"/reader.swf";wa=location.protocol+"//"+location.hostname+location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/pubData/";Da();V()};c.onerror=function(){ya();V()};c.src=a}
function Aa(){var a=window.speedloaderURLVar+ta+window.eMagStudioVersionVar+"/test.jpg",c=new Image;c.onload=function(){window.useSpeedloaderVar=k;window.useHostedSpeedloaderVar=w;va=window.speedloaderURLVar+ta+window.eMagStudioVersionVar+"/reader.swf";wa=location.protocol+"//"+location.hostname+location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/pubData/";Da();V()};c.onerror=function(){ya();V()};c.src=a}function ya(){window.useSpeedloaderVar=w;va="reader.swf";wa="pubData/";Da()}
function Da(){U.useSpeedloader=window.useSpeedloaderVar;U.useHostedSpeedloader=window.useHostedSpeedloaderVar;U.speedloaderURL=window.speedloaderURLVar;U.eMagStudioVersion=window.eMagStudioVersionVar;U.pubDataURL=wa;U.userAgent=navigator.userAgent;U.HREF=document.location.href}
function V(){window.params||(document.getElementById("eMag").innerHTML="<table width='100%' height='100%' border='0'><tr><td width='100%' align='center' valign='middle'><br><strong>You need to upgrade your Flash Player</strong><br>Viewing this eBook requires Adobe Flash Player version 11.1.0 or above.<br>Click below to download the latest version:<br><a href='http://www.adobe.com/go/getflashplayer'><img src='pubData/source/images/get_flash_player.gif' border='0' width='88' height='31' /></a></td></tr></table>",window.swfobject.embedSWF(va,
"eMag","100%","100%","11.1.0",wa+"expressInstall.swf",U,{scale:"default",allowScriptAccess:"always",swliveconnect:"true",classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",pluginspage:"http://www.adobe.com/go/getflashplayer",type:"application/x-shockwave-flash",base:"",wmode:"window",bgcolor:"#ffffff",allowFullscreen:"true"},{id:"eMag",name:"eMag"}))}
window.swfobject=function(){function a(){if(!C){try{var b=g.getElementsByTagName("body")[0].appendChild(g.createElement("span"));b.parentNode.removeChild(b)}catch(d){return}C=k;for(var b=K.length,i=0;i<b;i++)K[i]()}}function c(b){C?b():K[K.length]=b}function D(b){if(typeof m.addEventListener!=o)m.addEventListener("load",b,w);else if(typeof g.addEventListener!=o)g.addEventListener("load",b,w);else if(typeof m.attachEvent!=o)O(m,b);else if("function"==typeof m.onload){var d=m.onload;m.onload=function(){d();
b()}}else m.onload=b}function p(){var b=g.getElementsByTagName("body")[0],d=g.createElement(s);d.setAttribute("type",T);var i=b.appendChild(d);if(i){var F=0;(function(){if(typeof i.GetVariable!=o){var j=i.GetVariable("$version");j&&(j=j.split(" ")[1].split(","),e.g=[parseInt(j[0],10),parseInt(j[1],10),parseInt(j[2],10)])}else if(10>F){F++;setTimeout(arguments.callee,10);return}b.removeChild(d);i=u;x()})()}else x()}function x(){var b=E.length;if(0<b)for(var d=0;d<b;d++){var i=E[d].id,F=E[d].A,j={h:w,
id:i};if(0<e.g[0]){var a=z(i);if(a)if(B(E[d].N)&&!(e.c&&312>e.c))h(i,k),F&&(j.h=k,j.u=r(i),F(j));else if(E[d].p&&I()){j={};j.data=E[d].p;j.width=a.getAttribute("width")||"0";j.height=a.getAttribute("height")||"0";a.getAttribute("class")&&(j.ca=a.getAttribute("class"));a.getAttribute("align")&&(j.align=a.getAttribute("align"));for(var g={},a=a.getElementsByTagName("param"),f=a.length,c=0;c<f;c++)"movie"!=a[c].getAttribute("name").toLowerCase()&&(g[a[c].getAttribute("name")]=a[c].getAttribute("value"));
R(j,g,i,F)}else P(a),F&&F(j)}else if(h(i,k),F){if((i=r(i))&&typeof i.SetVariable!=o)j.h=k,j.u=i;F(j)}}}function r(b){var d=u;if((b=z(b))&&"OBJECT"==b.nodeName)typeof b.SetVariable!=o?d=b:(b=b.getElementsByTagName(s)[0])&&(d=b);return d}function I(){return!L&&B("6.0.65")&&(e.b||e.s)&&!(e.c&&312>e.c)}function R(b,d,i,a){L=k;f=a||u;la={h:w,id:i};var j=z(i);if(j){"OBJECT"==j.nodeName?(l=G(j),H=u):(l=j,H=i);b.id=Q;if(typeof b.width==o||!/%$/.test(b.width)&&310>parseInt(b.width,10))b.width="310";if(typeof b.height==
o||!/%$/.test(b.height)&&137>parseInt(b.height,10))b.height="137";g.title=g.title.slice(0,47)+" - Flash Player Installation";a=e.a&&e.b?"ActiveX":"PlugIn";a="MMredirectURL="+m.location.toString().replace(/&/g,"%26")+"&MMplayerType="+a+"&MMdoctitle="+g.title;d.flashvars=typeof d.flashvars!=o?d.flashvars+("&"+a):a;e.a&&(e.b&&4!=j.readyState)&&(a=g.createElement("div"),i+="SWFObjectNew",a.setAttribute("id",i),j.parentNode.insertBefore(a,j),j.style.display="none",function(){j.readyState==4?j.parentNode.removeChild(j):
setTimeout(arguments.callee,10)}());da(b,d,i)}}function P(b){if(e.a&&e.b&&4!=b.readyState){var d=g.createElement("div");b.parentNode.insertBefore(d,b);d.parentNode.replaceChild(G(b),d);b.style.display="none";(function(){4==b.readyState?b.parentNode.removeChild(b):setTimeout(arguments.callee,10)})()}else b.parentNode.replaceChild(G(b),b)}function G(b){var d=g.createElement("div");if(e.b&&e.a)d.innerHTML=b.innerHTML;else if(b=b.getElementsByTagName(s)[0])if(b=b.childNodes)for(var i=b.length,a=0;a<i;a++)!(1==
b[a].nodeType&&"PARAM"==b[a].nodeName)&&8!=b[a].nodeType&&d.appendChild(b[a].cloneNode(k));return d}function da(b,d,i){var a,j=z(i);if(e.c&&312>e.c)return a;if(j)if(typeof b.id==o&&(b.id=i),e.a&&e.b){var c="",n;for(n in b)b[n]!=Object.prototype[n]&&("data"==n.toLowerCase()?d.movie=b[n]:"styleclass"==n.toLowerCase()?c+=' class="'+b[n]+'"':"classid"!=n.toLowerCase()&&(c+=" "+n+'="'+b[n]+'"'));n="";for(var f in d)d[f]!=Object.prototype[f]&&(n+='<param name="'+f+'" value="'+d[f]+'" />');j.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+
c+">"+n+"</object>";y[y.length]=b.id;a=z(b.id)}else{f=g.createElement(s);f.setAttribute("type",T);for(var h in b)b[h]!=Object.prototype[h]&&("styleclass"==h.toLowerCase()?f.setAttribute("class",b[h]):"classid"!=h.toLowerCase()&&f.setAttribute(h,b[h]));for(c in d)d[c]!=Object.prototype[c]&&"movie"!=c.toLowerCase()&&(b=f,n=c,h=d[c],i=g.createElement("param"),i.setAttribute("name",n),i.setAttribute("value",h),b.appendChild(i));j.parentNode.replaceChild(f,j);a=f}return a}function X(b){var d=z(b);d&&"OBJECT"==
d.nodeName&&(e.a&&e.b?(d.style.display="none",function(){if(4==d.readyState){var i=z(b);if(i){for(var a in i)"function"==typeof i[a]&&(i[a]=u);i.parentNode.removeChild(i)}}else setTimeout(arguments.callee,10)}()):d.parentNode.removeChild(d))}function z(b){var d=u;try{d=g.getElementById(b)}catch(a){}return d}function O(b,d){b.attachEvent("onload",d);Y[Y.length]=[b,"onload",d]}function B(b){var d=e.g,b=b.split(".");b[0]=parseInt(b[0],10);b[1]=parseInt(b[1],10)||0;b[2]=parseInt(b[2],10)||0;return d[0]>
b[0]||d[0]==b[0]&&d[1]>b[1]||d[0]==b[0]&&d[1]==b[1]&&d[2]>=b[2]?k:w}function Z(b,d,a,c){if(!e.a||!e.s){var j=g.getElementsByTagName("head")[0];if(j){a=a&&"string"==typeof a?a:"screen";c&&(q=J=u);if(!J||q!=a)c=g.createElement("style"),c.setAttribute("type","text/css"),c.setAttribute("media",a),J=j.appendChild(c),e.a&&(e.b&&typeof g.styleSheets!=o&&0<g.styleSheets.length)&&(J=g.styleSheets[g.styleSheets.length-1]),q=a;e.a&&e.b?J&&typeof J.addRule==s&&J.addRule(b,d):J&&typeof g.createTextNode!=o&&J.appendChild(g.createTextNode(b+
" {"+d+"}"))}}}function h(b,d){if(ea){var a=d?"visible":"hidden";C&&z(b)?z(b).style.visibility=a:Z("#"+b,"visibility:"+a)}}function A(b){return/[\\\"<>\.;]/.exec(b)!=u&&typeof encodeURIComponent!=o?encodeURIComponent(b):b}var o="undefined",s="object",T="application/x-shockwave-flash",Q="SWFObjectExprInst",m=window,g=document,M=navigator,$=w,K=[function(){$?p():x()}],E=[],y=[],Y=[],l,H,f,la,C=w,L=w,J,q,ea=k,e=function(){var b=typeof g.getElementById!=o&&typeof g.getElementsByTagName!=o&&typeof g.createElement!=
o,d=M.userAgent.toLowerCase(),a=M.platform.toLowerCase(),c=a?/win/.test(a):/win/.test(d),a=a?/mac/.test(a):/mac/.test(d),d=/webkit/.test(d)?parseFloat(d.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):w,e=!+"\v1",f=[0,0,0],h=u;if(typeof M.plugins!=o&&typeof M.plugins["Shockwave Flash"]==s){if((h=M.plugins["Shockwave Flash"].description)&&!(typeof M.mimeTypes!=o&&M.mimeTypes[T]&&!M.mimeTypes[T].enabledPlugin))$=k,e=w,h=h.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),f[0]=parseInt(h.replace(/^(.*)\..*$/,"$1"),10),
f[1]=parseInt(h.replace(/^.*\.(.*)\s.*$/,"$1"),10),f[2]=/[a-zA-Z]/.test(h)?parseInt(h.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof m.ActiveXObject!=o)try{var l=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(l&&(h=l.GetVariable("$version")))e=k,h=h.split(" ")[1].split(","),f=[parseInt(h[0],10),parseInt(h[1],10),parseInt(h[2],10)]}catch(G){}return{d:b,g:f,c:d,a:e,b:c,s:a}}();(function(){e.d&&((typeof g.readyState!=o&&"complete"==g.readyState||typeof g.readyState==o&&(g.getElementsByTagName("body")[0]||
g.body))&&a(),C||(typeof g.addEventListener!=o&&g.addEventListener("DOMContentLoaded",a,w),e.a&&e.b&&(g.attachEvent("onreadystatechange",function(){"complete"==g.readyState&&(g.detachEvent("onreadystatechange",arguments.callee),a())}),m==top&&function(){if(!C){try{g.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}()),e.c&&function(){C||(/loaded|complete/.test(g.readyState)?a():setTimeout(arguments.callee,0))}(),D(a)))})();(function(){e.a&&e.b&&window.attachEvent("onunload",
function(){for(var b=Y.length,d=0;d<b;d++)Y[d][0].detachEvent(Y[d][1],Y[d][2]);b=y.length;for(d=0;d<b;d++)X(y[d]);for(var a in e)e[a]=u;e=u;for(var c in window.swfobject)window.swfobject[c]=u;window.swfobject=u})})();return{v:function(b,d,a,c){if(e.d&&b&&d){var f={};f.id=b;f.N=d;f.p=a;f.A=c;E[E.length]=f;h(b,w)}else c&&c({h:w,id:b})},V:function(b){if(e.d)return r(b)},embedSWF:function(b,d,a,f,g,l,n,m,G,P){var q={h:w,id:d};e.d&&!(e.c&&312>e.c)&&b&&d&&a&&f&&g?(h(d,w),c(function(){a+="";f+="";var c=
{};if(G&&typeof G===s)for(var e in G)c[e]=G[e];c.data=b;c.width=a;c.height=f;e={};if(m&&typeof m===s)for(var t in m)e[t]=m[t];if(n&&typeof n===s)for(var na in n)e.flashvars=typeof e.flashvars!=o?e.flashvars+("&"+na+"="+n[na]):na+"="+n[na];if(B(g))t=da(c,e,d),c.id==d&&h(d,k),q.h=k,q.u=t;else{if(l&&I()){c.data=l;R(c,e,d,P);return}h(d,k)}P&&P(q)})):P&&P(q)},da:function(){ea=w},ea:e,U:function(){return{J:e.g[0],Y:e.g[1],$:e.g[2]}},X:B,o:function(b,a,c){if(e.d)return da(b,a,c)},ba:function(b,a,c,f){e.d&&
I()&&R(b,a,c,f)},aa:function(b){e.d&&X(b)},R:function(b,a,c,f){e.d&&Z(b,a,c,f)},O:c,P:D,W:function(b){var a=g.location.search||g.location.hash;if(a){/\?/.test(a)&&(a=a.split("?")[1]);if(b==u)return A(a);for(var a=a.split("&"),c=0;c<a.length;c++)if(a[c].substring(0,a[c].indexOf("="))==b)return A(a[c].substring(a[c].indexOf("=")+1))}return""},S:function(){if(L){var b=z(Q);b&&l&&(b.parentNode.replaceChild(l,b),H&&(h(H,k),e.a&&e.b&&(l.style.display="block")),f&&f(la));L=w}}}}();
if("undefined"==typeof Ea)var Ea={};if("undefined"==typeof Fa)var Fa={};
Fa.k=new function(){var a=navigator.userAgent.toLowerCase(),c=/webkit/.test(a),D=/opera/.test(a),p=/msie/.test(a)&&!/opera/.test(a),x=/mozilla/.test(a)&&!/(compatible|webkit)/.test(a),r=parseFloat(p?a.substr(a.indexOf("msie")+4):(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1]);this.toString=ba("[class Browser]");this.D=function(){return r};this.r=function(){return p};this.l=function(){return c};this.I=function(){return D};this.H=function(){return x}};
Fa.n=new function(){function a(){if("interactive"==p.readyState){var a=function(){p.detachEvent("onstop",a);c()};p.attachEvent("onstop",a);D.setTimeout(function(){p.detachEvent("onstop",a)},0)}}function c(){for(var a=0,c;c=x[a];a++)"DOMContentLoaded"!=c.j&&Fa.n.M(c.t,c.j,c.m)}var D=window,p=document,x=[],r=Fa.k,I=r.r(),R=r.l();this.toString=ba("[class Events]");this.i=function(a,c,p){x.push({t:a,j:c,m:p});"DOMContentLoaded"==c&&(I||R)||(a.addEventListener?a.addEventListener(c,p,w):a.attachEvent&&
a.attachEvent("on"+c,p))};this.M=function(a,c,p){for(var r=0,z;z=x[r];r++)if(z.t==a&&z.j==c&&z.m==p){x.splice(r,1);break}"DOMContentLoaded"==c&&(I||R)||(a.removeEventListener?a.removeEventListener(c,p,w):a.detachEvent&&a.detachEvent("on"+c,p))};(I||R)&&function(){try{(I&&p.body||!/loaded|complete/.test(p.readyState))&&p.documentElement.doScroll("left")}catch(a){return setTimeout(arguments.callee,0)}for(var c=0,r;r=x[c];c++)"DOMContentLoaded"==r.j&&r.m.call(u)}();I&&D.attachEvent("onbeforeunload",
a);this.i(D,"unload",c)};Fa.z=new function(){this.toString=ba("[class Functions]");this.bind=function(a,c,D){for(var p=2,x,r=[];x=arguments[p];p++)r.push(x);return function(){return a.apply(c,r)}}};
function Ga(a){this.toString=ba("[object SWFAddressEvent]");this.type=a;this.target=window.SWFAddress;this.value=window.SWFAddress.e();this.path=window.SWFAddress.q();window.SWFAddress.C();this.K={};for(var a=window.SWFAddress.B(),c=0,D=a.length;c<D;c++)this.K[a[c]]=window.SWFAddress.getParameter(a[c]);this.parameterNames=a}
window.SWFAddress=new function(){function a(){if(!F){F=A;if(g&&8>m){var t=l.getElementsByTagName("frameset")[0];q=l.createElement((t?"":"i")+"frame");t?(t.G("beforeEnd",q),t[t.cols?"cols":"rows"]+=",0",q.src="javascript:false",q.noResize=k,q.frameBorder=q.T=0):(q.src="javascript:false",q.style.display="none",l.body.G("afterBegin",q));C(function(){T.i(q,"load",c);typeof q.contentWindow[B]==h&&D()},50)}else K&&(418>m&&(l.body.innerHTML+='<form id="'+B+'" style="position:absolute;top:-9999px;" method="get"></form>',
ea=l.getElementById(B)),typeof f[B]==h&&(f[B]={}),typeof f[B][f.pathname]!=h&&(W=f[B][f.pathname].split(",")));C(Q.bind(function(){o.k.l()&&l.body.addEventListener("click",R);r.call(this,"init");I();r.call(this,"change");p.call(this)},this),1);g&&8<=m?(l.body.onhashchange=Q.bind(P,this),la(Q.bind(G,this),50)):la(Q.bind(P,this),50)}}function c(){var t=q.contentWindow;v=typeof t[B]!=h?t[B]:"";v!=O()&&(x.call(window.SWFAddress,w),f.hash=X(v,A))}function D(){var t=q.contentWindow.document;t.open();t.write("<html><head><title>"+
l.title+"</title><script>var "+B+' = "'+O()+'";<\/script></head></html>');t.close()}function p(){var t=(f.pathname+(/\/$/.test(f.pathname)?"":"/")+this.e()).replace(/\/\//,"/").replace(/^\/$/,""),a=y[window._opts.tracker];typeof a==Z?a(t):typeof y.pageTracker!=h&&typeof y.pageTracker._trackPageview==Z?y.pageTracker._trackPageview(t):typeof y.urchinTracker==Z&&y.urchinTracker(t)}function x(a){I();r.call(this,"change");a?r.call(this,"internalChange"):r.call(this,"externalChange");C(Q.bind(p,this),10)}
function r(a){this.dispatchEvent(new Ga(a));a=a.substr(0,1).toUpperCase()+a.substr(1);if(typeof this["on"+a]==Z)this["on"+a]()}function I(){for(var a=0,b,c,d=window.SWFAddress.e();b=ka[a];a++)(c=document.getElementById(b))?c.parentNode&&typeof c.parentNode.w!=h?c.parentNode.w.call("setSWFAddressValue",d):(c&&typeof c.setSWFAddressValue!=h||(b=c.getElementsByTagName("object"),c=c.getElementsByTagName("embed"),c=b[0]&&typeof b[0].setSWFAddressValue!=h?b[0]:c[0]&&typeof c[0].setSWFAddressValue!=h?c[0]:
u),c&&c.setSWFAddressValue(d)):(c=document[b])&&typeof c.setSWFAddressValue!=h&&c.setSWFAddressValue(d)}function R(){0<aa.length&&(window.open(aa[0],aa[1],eval(aa[2])),typeof aa[3]!=h&&eval(aa[3]));aa=[]}function P(){if(!i){var a=O(),b=v!=a;K&&523>m?d!=H.length&&(d=H.length,typeof W[d-1]!=h&&(v=W[d-1]),x.call(this,w)):g&&b?7>m?f.reload():this.setValue(a):b&&(v=a,x.call(this,w));g&&G.call(this)}}function G(){l.title!=b&&-1!=l.title.indexOf("#")&&(l.title=b)}function da(a){if(a.childNodes)for(var b=
0,c=a.childNodes.length,d;b<c;b++)if(a.childNodes[b].src&&(e=""+a.childNodes[b].src),d=da(a.childNodes[b]))return d}function X(a,b){return g&&"file:"==f.protocol?b?v.replace(/\?/,"%3F"):v.replace(/%253F/,"?"):a}function z(a,b){window._opts.strict&&(a=b?"/"!=a.substr(0,1)?"/"+a:a:""==a?"/":a);return a}function O(){var a=f.href.indexOf("#");return-1!=a?J(L(f.href.substr(a+1))):""}var B="swfaddress",Z="function",h="undefined",A=k,o=Fa,s=o.k,T=o.n,Q=o.z,m=s.D(),g=s.r(),M=s.H(),$=s.I(),K=s.l(),E=w,y;try{top.document,
y=top}catch(Y){y=window}var l=y.document,H=y.history,f=y.location,la=setInterval,C=setTimeout,L=decodeURI,J=encodeURI,q,ea,e,b=l.title,d=H.length,i=w,F=w,j=A,Ca=A,n=this,W=[],ka=[],aa=[],S={},v=O();window._opts={history:A,strict:A};g&&(l.documentMode&&l.documentMode!=m)&&(m=8!=l.documentMode?7:8);if(E=M&&1<=m||g&&6<=m||$&&9.5<=m||K&&312<=m){$&&(history.Z="compatible");for(s=1;s<d;s++)W.push("");W.push(O());g&&f.hash!=O()&&(f.hash="#"+X(O(),A));da(document);s=e?e.indexOf("?"):-1;if(-1!=s)for(var N,
$=e.substr(s+1).split("&"),s=0;N=$[s];s++)N=N.split("="),/^(history|strict)$/.test(N[0])&&(window._opts[N[0]]=isNaN(N[1])?/^(true|yes)$/i.test(N[1]):0!=parseInt(N[1])),/^tracker$/.test(N[0])&&(window._opts[N[0]]=N[1]);g&&G.call(this);window==y&&T.i(document,"DOMContentLoaded",Q.bind(a,this));T.i(y,"load",Q.bind(a,this))}else!E&&-1!=f.href.indexOf("#")||K&&418>m&&-1!=f.href.indexOf("#")&&""!=f.search?(l.open(),l.write('<html><head><meta http-equiv="refresh" content="0;url='+f.href.substr(0,f.href.indexOf("#"))+
'" /></head></html>'),l.close()):p();this.toString=ba("[class SWFAddress]");this.back=function(){H.back()};this.forward=function(){H.forward()};this.go=function(a){H.go(a)};this.href=function(a,b){b=typeof b!=h?b:"_self";"_self"==b?self.location.href=a:"_top"==b?f.href=a:"_blank"==b?window.open(a):y.frames[b].location.href=a};this.f=function(a){this.L(a);ka.push(a)};this.L=function(a){for(var b=0;b<ka.length;b++)if(a==ka[b]){ka.splice(b,1);break}};this.addEventListener=function(a,b){typeof S[a]==
h&&(S[a]=[]);S[a].push(b)};this.removeEventListener=function(a,b){if(typeof S[a]!=h){for(var c=0,d;(d=S[a][c])&&d!=b;c++);S[a].splice(c,1)}};this.dispatchEvent=function(a){if(this.F(a.type)){a.target=this;for(var b=0,c;c=S[a.type][b];b++)c(a);return A}return w};this.F=function(a){return typeof S[a]!=h&&0<S[a].length};this.setTitle=function(a){if(!E)return u;typeof a!=h&&("null"==a&&(a=""),a=L(a),C(function(){b=l.title=a;Ca&&(q&&q.contentWindow&&q.contentWindow.document)&&(q.contentWindow.document.title=
a,Ca=w);!j&&M&&f.replace(-1!=f.href.indexOf("#")?f.href:f.href+"#");j=w},10))};this.e=function(){return!E?u:L(z(X(v,w),w))};this.setValue=function(a){if(!E)return u;if(typeof a!=h&&("null"==a&&(a=""),a=J(L(z(a,A))),"/"==a&&(a=""),v!=a)){j=A;v=a;i=A;x.call(window.SWFAddress,k);W[H.length]=v;if(K)if(window._opts.history)if(f[B][f.pathname]=W.toString(),d=H.length+1,418>m)""==f.search&&(ea.action="#"+v,ea.submit());else if(523>m||""==v){a=l.createEvent("MouseEvents");a.initEvent("click",A,A);var b=l.createElement("a");
b.href="#"+v;b.dispatchEvent(a)}else f.hash="#"+v;else f.replace("#"+v);else v!=O()&&(window._opts.history?f.hash="#"+L(X(v,A)):f.replace("#"+L(v)));g&&8>m&&window._opts.history&&C(D,50);K?C(function(){i=w},1):i=w}};this.q=function(){var a=this.e();return-1!=a.indexOf("?")?a.split("?")[0]:-1!=a.indexOf("#")?a.split("#")[0]:a};this.C=function(){var a=this.q(),b=a.split("/");("/"==a.substr(0,1)||0==a.length)&&b.splice(0,1);"/"==a.substr(a.length-1,1)&&b.splice(b.length-1,1)};this.getParameter=function(a){var b=
this.e(),c=b.indexOf("?");if(-1!=c){for(var b=b.substr(c+1),c=b.split("&"),d=c.length,e=[];d--;)b=c[d].split("="),b[0]==a&&e.push(b[1]);if(0!=e.length)return 1!=e.length?e:e[0]}};this.B=function(){var a=this.e(),b=a.indexOf("?"),c=[];if(-1!=b&&(a=a.substr(b+1),""!=a&&-1!=a.indexOf("="))){a=a.split("&");for(b=0;b<a.length;)c.push(a[b].split("=")[0]),b++}return c};(function(){var a;typeof FlashObject!=h&&(SWFObject=FlashObject);if(typeof SWFObject!=h&&SWFObject.prototype&&SWFObject.prototype.write){var b=
SWFObject.prototype.write;SWFObject.prototype.write=function(){a=arguments;8>this.getAttribute("version").J&&(this.Q("$swfaddress",window.SWFAddress.e()),("string"==typeof a[0]?document.getElementById(a[0]):a[0]).w=this);var c;(c=b.apply(this,a))&&n.f(this.getAttribute("id"));return c}}if(typeof window.swfobject!=h){var c=window.swfobject.v;window.swfobject.v=function(){a=arguments;c.apply(this,a);n.f(a[0])};var d=window.swfobject.o;window.swfobject.o=function(){a=arguments;var b=d.apply(this,a);
b&&n.f(a[0].id);return b};var e=window.swfobject.embedSWF;window.swfobject.embedSWF=function(){a=arguments;typeof a[8]==h&&(a[8]={});typeof a[8].id==h&&(a[8].id=a[1]);e.apply(this,a);n.f(a[8].id)}}if(typeof UFO!=h){var f=UFO.create;UFO.create=function(){a=arguments;f.apply(this,a);n.f(a[0].id)}}if(typeof AC_FL_RunContent!=h){var g=AC_FL_RunContent;AC_FL_RunContent=function(){a=arguments;g.apply(this,a);for(var b=0,c=a.length;b<c;b++)"id"==a[b]&&n.f(a[b+1])}}})()};